version: '3'
services:
  go_sample_mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
      - "33070:33060"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SOCKET: /var/lib/mysql/mysql.sock
      MYSQL_HOST: go_sample_db
    volumes:
      - ./mysql/data:/var/lib/mysql
  go_sample:
    build: ./sample/
    container_name: go_sample
    privileged: true
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - go_sample_mysql
      - go_sample_redis
    volumes:
      - ./sample:/go/src/go_sample
    ports:
      - "8080:8080"
  go_sample_redis:
    restart: always
    image: redis:alpine
    ports:
      - "6389:6379"
    command: redis-server --appendonly yes
volumes:
  vendor:
