version: '3'
services:
  go_sample_mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
      - "33070:33060"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SOCKET: "/var/lib/mysql/mysql.sock"
      MYSQL_HOST: go_sample_db
    volumes:
      - ./mysql/volumes:/var/lib/mysql
  go_sample:
    build: .
    container_name: go_sample
    privileged: true
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - go_sample_mysql
    volumes:
      - .:/go/src/go_sample
      - ./../sample_vendor:/go/src/go_sample/vendor
    ports:
      - "8080:8080"
volumes:
  vendor:
  mysql-data:
